## Note: This docker-compose file will only set up pi-hole to handle dns requests ##
# it does not handle DCHP, NTP and other system server prmission - look at the links below.
# Lastly, you will need to point your devices to send dns requests to the server ip address
# I recommend to update your routers dns ip and chagne it to the appropriate ip.  

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
# https://github.com/pi-hole/docker-pi-hole#note-on-capabilities

services:
  pihole:
    hostname: pihole # added this show it does not show long hex string in web UI
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp" # DNS
      - "53:53/udp"
      - "8181:80/tcp" # web UI 
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'changeme' # 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole' # setting vol to be in same folder
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
