## NOTE: This is pihone version 5 is outdate 

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
# https://github.com/pi-hole/docker-pi-hole#note-on-capabilities

# !!! VERSIONS SINCE 2025.02.0 CONTAIN BREAKING CHANGES IF UPGRADING FROM 2024.07.0 OR OLDER
# https://hub.docker.com/r/pihole/pihole

services:
  pihole:
    hostname: pihole # added this show it does not show long hex string in web UI
    container_name: pihole
    image: pihole/pihole:2024.07.0
    ports:
      - "53:53/tcp" # DNS
      - "53:53/udp"
      - "8181:80/tcp" # web UI 
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'changeme' # 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole' # setting vol to be in same folder
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
